package cn.wawi.model.business;

import cn.wawi.model.sys.base.BaseAgentscustomeremployee;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Agentscustomeremployee extends BaseAgentscustomeremployee<Agentscustomeremployee> {
	public static final Agentscustomeremployee dao = new Agentscustomeremployee();
}
