package cn.wawi.model.business;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import cn.wawi.model.sys.base.BaseMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Member extends BaseMember<Member> {
	public static final Member dao = new Member();
	
	
	public List<Record> getMemberServices(String memberId){
		return Db.find("select serviceid id from memberservice where memberid=?",memberId);
	}
	
	public Record getMemberById(String id){
		return Db.findById("member", id);
	}
	
}
