package cn.wawi.model.business;

import cn.wawi.model.sys.base.BaseMemberservice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Memberservice extends BaseMemberservice<Memberservice> {
	public static final Memberservice dao = new Memberservice();
}
