package cn.wawi.model.business;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import cn.wawi.model.sys.base.BaseServicecategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Servicecategory extends BaseServicecategory<Servicecategory> {
	public static final Servicecategory dao = new Servicecategory();
	
	public List<Record> getCategorys (){
		return    Db.find(" select * from servicecategory where deleted !=1 ");
	}
}
