package cn.wawi.model.business;

import cn.wawi.model.sys.base.BaseServiceitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Serviceitem extends BaseServiceitem<Serviceitem> {
	public static final Serviceitem dao = new Serviceitem();
}
