package cn.wawi.model.sys.base;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {
	

	public BaseUser(){
		set("inputTime", new Date());
	}
	
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}

	public java.lang.String getRealname() {
		return get("realname");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setGeneder(java.lang.Integer geneder) {
		set("geneder", geneder);
	}

	public java.lang.Integer getGeneder() {
		return get("geneder");
	}

	public void setInputTime(java.util.Date inputTime) {
		set("inputTime", inputTime);
	}
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public java.util.Date getInputTime() {
		return get("inputTime");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setDepartmentId(java.lang.Integer departmentId) {
		set("departmentId", departmentId);
	}

	public java.lang.Integer getDepartmentId() {
		return get("departmentId");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

}
