package cn.wawi.model.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAgentsservice<M extends BaseAgentsservice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAgentsid(java.lang.Integer agentsid) {
		set("agentsid", agentsid);
	}

	public java.lang.Integer getAgentsid() {
		return get("agentsid");
	}

	public void setServiceid(java.lang.Integer serviceid) {
		set("serviceid", serviceid);
	}

	public java.lang.Integer getServiceid() {
		return get("serviceid");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
