package cn.wawi.model.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMemberservice<M extends BaseMemberservice<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMemberid(java.lang.Integer memberid) {
		set("memberid", memberid);
	}

	public java.lang.Integer getMemberid() {
		return get("memberid");
	}

	public void setServiceid(java.lang.Integer serviceid) {
		set("serviceid", serviceid);
	}

	public java.lang.Integer getServiceid() {
		return get("serviceid");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setStartTime(java.util.Date startTime) {
		set("startTime", startTime);
	}

	public java.util.Date getStartTime() {
		return get("startTime");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}

	public java.util.Date getEndTime() {
		return get("endTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setPayway(java.lang.String payway) {
		set("payway", payway);
	}

	public java.lang.String getPayway() {
		return get("payway");
	}

	public void setTime(java.lang.Integer time) {
		set("time", time);
	}

	public java.lang.Integer getTime() {
		return get("time");
	}

}
