package cn.wawi.model.sys.base;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {
	
	public BaseLog(){
		set("inputTime", new Date());
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setOptUser(java.lang.String optUser) {
		set("optUser", optUser);
	}

	public java.lang.String getOptUser() {
		return get("optUser");
	}

	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}

	public java.lang.String getRealname() {
		return get("realname");
	}

	public void setInputTime(java.util.Date inputTime) {
		set("inputTime", inputTime);
	}
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public java.util.Date getInputTime() {
		return get("inputTime");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setIsSuccess(java.lang.String isSuccess) {
		set("isSuccess", isSuccess);
	}

	public java.lang.String getIsSuccess() {
		return get("isSuccess");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setOs(java.lang.String os) {
		set("os", os);
	}

	public java.lang.String getOs() {
		return get("os");
	}

	public void setBrowser(java.lang.String browser) {
		set("browser", browser);
	}

	public java.lang.String getBrowser() {
		return get("browser");
	}

	public void setRequestParam(java.lang.String requestParam) {
		set("requestParam", requestParam);
	}

	public java.lang.String getRequestParam() {
		return get("requestParam");
	}

	public void setOperationCode(java.lang.String operationCode) {
		set("operationCode", operationCode);
	}

	public java.lang.String getOperationCode() {
		return get("operationCode");
	}

}
