package cn.wawi.model.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePayrecord<M extends BasePayrecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setMemberid(java.lang.Integer memberid) {
		set("memberid", memberid);
	}

	public java.lang.Integer getMemberid() {
		return get("memberid");
	}

	public void setMoney(java.lang.String money) {
		set("money", money);
	}

	public java.lang.String getMoney() {
		return get("money");
	}

	public void setCount(java.lang.String count) {
		set("count", count);
	}

	public java.lang.String getCount() {
		return get("count");
	}

	public void setPayway(java.lang.Boolean payway) {
		set("payway", payway);
	}

	public java.lang.Boolean getPayway() {
		return get("payway");
	}

	public void setUserid(java.lang.String userid) {
		set("userid", userid);
	}

	public java.lang.String getUserid() {
		return get("userid");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setServiceid(java.lang.Integer serviceid) {
		set("serviceid", serviceid);
	}

	public java.lang.Integer getServiceid() {
		return get("serviceid");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}
	
	public void setDeleted(java.lang.Boolean deleted){
		set("deleted",deleted);
	}
	
	public java.lang.Boolean getDeleted(){
		return get("deleted");
	}

}
