package cn.wawi.model.sys.base;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePrivilege<M extends BasePrivilege<M>> extends Model<M> implements IBean {

	public String state="closed";
	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setIconCls(java.lang.String iconCls) {
		set("iconCls", iconCls);
	}

	public java.lang.String getIconCls() {
		return get("iconCls");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setUrl(java.lang.String url) {
		set("url", url);
	}

	public java.lang.String getUrl() {
		return get("url");
	}

	public void setDescription(java.lang.String description) {
		set("description", description);
	}

	public java.lang.String getDescription() {
		return get("description");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parentId", parentId);
	}
	@JsonProperty("_parentId")
	public java.lang.Integer getParentId() {
		return get("parentId");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setPermCode(java.lang.String permCode) {
		set("permCode", permCode);
	}

	public java.lang.String getPermCode() {
		return get("permCode");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}
    
	public void setDeleted(java.lang.Boolean deleted){
		set("deleted",deleted);
	}
	
	public java.lang.Boolean getDeleted(){
		return get("deleted");
	}
	
}
