package cn.wawi.model.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMember<M extends BaseMember<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCellphone(java.lang.String cellphone) {
		set("cellphone", cellphone);
	}

	public java.lang.String getCellphone() {
		return get("cellphone");
	}

	public void setCarnumber(java.lang.String carnumber) {
		set("carnumber", carnumber);
	}

	public java.lang.String getCarnumber() {
		return get("carnumber");
	}

	public void setStatus(java.lang.Boolean status) {
		set("status", status);
	}

	public java.lang.Boolean getStatus() {
		return get("status");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

	public void setRemarker(java.lang.String remarker) {
		set("remarker", remarker);
	}

	public java.lang.String getRemarker() {
		return get("remarker");
	}

	public void setUserid(java.lang.Integer userid) {
		set("userid", userid);
	}

	public java.lang.Integer getUserid() {
		return get("userid");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public void setMoney(java.math.BigDecimal money) {
		set("money", money);
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public void setTotalcount(java.lang.Integer totalcount) {
		set("totalcount", totalcount);
	}

	public java.lang.Integer getTotalcount() {
		return get("totalcount");
	}

	public void setDeleted(java.lang.Boolean deleted) {
		set("deleted", deleted);
	}

	public java.lang.Boolean getDeleted() {
		return get("deleted");
	}

	public void setEndTime(java.util.Date endTime) {
		set("endTime", endTime);
	}

	public java.util.Date getEndTime() {
		return get("endTime");
	}
    
	
	public java.lang.Integer getCheckStatus(){
		return get("checkStatus");
	}
	
	public void setCheckStatus(java.lang.Integer checkStatus){
		set("checkStatus",checkStatus);
	}
	
}
