package cn.wawi.model.sys;

import cn.wawi.model.sys.base.BaseAgentsservice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Agentsservice extends BaseAgentsservice<Agentsservice> {
	public static final Agentsservice dao = new Agentsservice();
}
