package cn.wawi.model.sys;

import cn.wawi.model.sys.base.BaseDict;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dict extends BaseDict<Dict> {
	public static final Dict dao = new Dict();
}
