package cn.wawi.model.sys;

import cn.wawi.model.sys.base.BaseDictitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dictitem extends BaseDictitem<Dictitem> {
	public static final Dictitem dao = new Dictitem();
}
