package cn.wawi.model.sys;

import cn.wawi.model.sys.base.BaseMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Member extends BaseMember<Member> {
	public static final Member dao = new Member();
}
