package cn.wawi.model.sys;

import cn.wawi.model.sys.base.BasePayrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Payrecord extends BasePayrecord<Payrecord> {
	public static final Payrecord dao = new Payrecord();
}
