package cn.wawi.model.sys;

import java.util.List;
import java.util.Map;
import com.jfinal.plugin.activerecord.Db;
import cn.wawi.model.sys.base.BasePrivilege;
import cn.wawi.utils.DbUtil;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Privilege extends BasePrivilege<Privilege> {
	public static final Privilege dao = new Privilege();
	
	/**
	 * 查询登录用户的权限-树
	 */
	public List<Map<String,Object>> findUserPermission(Object userId,String type){
		return DbUtil.findTree(Db.find("select id,iconCls,name,url,description,parentId, permCode from sys_module where userId=? and type='F' group by id ",new Object[]{userId}));
	}
}
