package cn.wawi.model.sys;

import cn.wawi.model.sys.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	/**
	 *  用户登录
	 */
	public User login(String username,String password){
		return findFirst("select * from sys_user where username=? and password=?",new Object[]{username,password});
	}
}
